### ISSUE TITLE
我的树莓派放不出声音

### ISSUE THREAD

**Issue by ghost** [yaphone/RasWxNeteaseMusic#15]

**Comment by ghost** [comment]
Traceback (most recent call last):
  File "/home/pi/RasWxNeteaseMusic-master/itchat/components/login.py", line 199, in maintain_loop
    i = sync_check(self)
  File "/home/pi/RasWxNeteaseMusic-master/itchat/components/login.py", line 250, in sync_check
    r = self.s.get(url, params=params, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine('HTTP/1.1 0 -\r\n',))
