### ISSUE TITLE
关于微信扫码的问题

### ISSUE THREAD

**Issue by bangbang37** [yaphone/RasWxNeteaseMusic#7]
您好，关于微信扫码的问题前一个版本的扫码可以顺利进行，而这个版本出现的二维码会出现错乱的情况。请问这是为什么呢？谢谢

**Comment by yaphone** [comment]
你好，朋友，我的并没有遇到二维码错乱的问题，我引用另一位朋友@BlackZheng的答案，你试试能不能解决：

编辑run.py 作以下修改可解决你的问题
如部分的linux系统，块字符的宽度为一个字符（正常应为两字符），故赋值为2
itchat.auto_login(enableCmdQR=2)

如果还不能解决的话，每次登陆的时候可以手动打开itchat目录，在目录下会生成一张名为`QR.jpg`的二维码图片，打开扫描即可。

祝使用愉快。

**Comment by bangbang37** [comment]
的确是字符宽度的问题。已经解决了。谢谢~

**Comment by bangbang37** [comment]
您好，还有一件事情需要请教您，我在登录网易云账号的时候碰到两个问题，第一个是密码中出现符号会直接显示输入错误。第二个是我重新注册了一个账号，但是输完账号密码每次都是回复登录失败，请问这是为什么呢？谢谢！

**Comment by yaphone** [comment]
L 账号 密码之间需要加空格分隔。

**Comment by bangbang37** [comment]
我有加空格，但是还是不行。请问登录账号有限制吗？比如只能是网易邮箱之类的？如果用网易邮箱，我账号密码还有L之间都空一格，但是发送以后还是会显示登录失败。我上网站登录这个账号是可以正常登录的。
现实的信息是：Request to send a text message to @b7a3dbc1458d5d2f5041b5106f54895a: 登陆失败

**Comment by bangbang37** [comment]
我刚刚试了一下，可能还是因为字符宽度的原因，我直接空两格不会显示登录失败，但是会显示：
An error occurred in registered function, use `itchat.run(debug=True)` to show detailed information
Traceback (most recent call last):
  File "/home/pi/RasWxNeteaseMusic-master/itchat/components/register.py", line 66, in configured_reply
    r = replyFn(msg)
  File "run.py", line 9, in mp3_player
    res = wnm.msg_handler(text)
  File "/home/pi/RasWxNeteaseMusic-master/WxNeteaseMusic.py", line 172, in msg_handler
    return res
UnboundLocalError: local variable 'res' referenced before assignment
这个错误，请问这是什么原因呢？

**Comment by bangbang37** [comment]
问题解决了，是因为登陆的账号不能是有特殊符号的原因。但是具体原因我猜测可能是因为编码的问题所造成的。
现在又有另外一个问题，是歌曲播放的时候，没有声音。我用的是3.5的口直接插耳机播放的

**Comment by yaphone** [comment]
树莓派在开机检测到HDMI输出之后，会把音频定向到HDMI上，导致拔掉显示器后使用耳机口没有声音，这是我的猜测哈朋友，不一定正确。

至于脱离显示器播放音频的问题，可以使用SSH登陆树莓派，使用Linux下的 screen 命令，实现后台播放。

音量控制问题还有待进一步研究。

最后，祝使用愉快！

**Comment by bangbang37** [comment]
我是在SSH里运行的，我之前已经把default改成3.5的端口了，我试着执行@littlecodersh 的musicbox代码，是可以有声音的，但是您的是有显示在播放但是没有声音。我猜测会不会是音乐播放地址出了问题？
最后，谢谢您一直帮我解答问题，麻烦您了~

**Comment by yaphone** [comment]
可以把播放地址打印出来，在浏览器中打开看一下地址是不是有效的。
